# Generated by Django 4.2.8 on 2023-12-25 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='系名')),
                ('director', models.CharField(max_length=20, verbose_name='系主任')),
                ('phone', models.CharField(max_length=20, verbose_name='办公室电话')),
            ],
            options={
                'verbose_name': '系信息',
                'verbose_name_plural': '系信息',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='专业名')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_manage.department', verbose_name='所属系')),
            ],
            options={
                'verbose_name': '专业信息',
                'verbose_name_plural': '专业信息',
                'db_table': 'major',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('sno', models.CharField(max_length=20, verbose_name='学号')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=1, verbose_name='性别')),
                ('address', models.CharField(max_length=20, verbose_name='地址')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_manage.major', verbose_name='专业')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'student',
            },
        ),
    ]
