# Generated by Django 4.2.7 on 2023-11-08 09:07

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(help_text='活动名称', max_length=20, verbose_name='活动名称')),
                ('address', models.CharField(help_text='活动地址', max_length=50, verbose_name='活动地址')),
                ('start_time', models.DateTimeField(help_text='活动开始时间', verbose_name='活动开始时间')),
                ('end_time', models.DateTimeField(help_text='活动结束时间', verbose_name='活动结束时间')),
                ('number_limit', models.IntegerField(help_text='人数限制', verbose_name='人数限制')),
                ('detail', ckeditor.fields.RichTextField(blank=True, help_text='活动详情', null=True, verbose_name='活动详情')),
                ('status', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('creator', models.ForeignKey(help_text='创建者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'db_table': 'ta_activity',
            },
        ),
        migrations.CreateModel(
            name='ActivityUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('join_status', models.IntegerField(choices=[(1, '审核中'), (2, '审核通过'), (3, '审核失败'), (4, '已取消'), (5, '禁止参加')], default=1, help_text='加入状态', verbose_name='加入状态')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('activity', models.ForeignKey(help_text='活动', on_delete=django.db.models.deletion.CASCADE, to='activity.activity', verbose_name='活动')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '参加活动的用户',
                'verbose_name_plural': '参加活动的用户',
                'db_table': 'ta_activity_user',
            },
        ),
        migrations.CreateModel(
            name='ActivityBrowse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('activity', models.ForeignKey(help_text='活动', on_delete=django.db.models.deletion.CASCADE, to='activity.activity', verbose_name='活动')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '浏览活动的用户',
                'verbose_name_plural': '浏览活动的用户',
                'db_table': 'ta_activity_browse',
            },
        ),
    ]
