version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    restart: always
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: tabzxiaohu
      MYSQL_DATABASE: tabzxiaohu
      MYSQL_USER: tabzxiaohu
      MYSQL_PASSWORD: tabzxiaohu
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "4406:3306"
