# Generated by Django 4.2.7 on 2023-11-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '保密')], default=2, verbose_name='性别'),
        ),
    ]
