# Generated by Django 4.2.7 on 2023-11-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('man', '男'), ('women', '女'), ('secret', '保密')], default='secret', help_text='性别', max_length=50, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, help_text='个性签名', max_length=100, null=True, verbose_name='个性签名'),
        ),
    ]
