# Generated by Django 4.2.7 on 2023-11-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_sex_user_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='signature',
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('man', '男'), ('women', '女'), ('secret', '保密')], default='secret', max_length=50, verbose_name='性别'),
        ),
    ]
