# Generated by Django 4.2.7 on 2023-11-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_signature_user_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女'), (3, '保密')], default=3, verbose_name='性别'),
        ),
    ]
