# Generated by Django 4.2.7 on 2023-11-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_sex'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='verifycode',
            index=models.Index(fields=['mobile'], name='ta_verifyco_mobile_796474_idx'),
        ),
    ]
