# Generated by Django 4.2.7 on 2023-11-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_verifycode_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='openid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='openid'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, '小程序'), (1, 'h5'), (2, 'app')], default=1, verbose_name='用户类型'),
        ),
    ]
