# Generated by Django 4.2.7 on 2023-11-13 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_initial'),
        ('user', '0009_alter_user_mobile_alter_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.school', verbose_name='学校'),
        ),
    ]
