# Generated by Django 4.2.7 on 2023-11-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='%Y/%m/%d/', verbose_name='文件'),
        ),
    ]
