# Generated by Django 4.2.7 on 2023-11-08 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(help_text='学校名称', max_length=20, verbose_name='学校名称')),
                ('address', models.CharField(help_text='学校地址', max_length=50, verbose_name='学校地址')),
                ('status', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '学校',
                'verbose_name_plural': '学校',
                'db_table': 'ta_school',
            },
        ),
        migrations.CreateModel(
            name='SchoolUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('permission', models.IntegerField(choices=[(1, '管理员'), (2, '审核员'), (3, '代理商')], default=3, help_text='权限', verbose_name='权限')),
                ('is_disable', models.BooleanField(default=False, help_text='是否禁用', verbose_name='是否禁用')),
                ('group', models.ForeignKey(help_text='权限组', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='权限组')),
                ('school', models.ForeignKey(help_text='学校', on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='学校')),
            ],
            options={
                'verbose_name': '学校权限关联',
                'verbose_name_plural': '学校权限关联',
                'db_table': 'ta_school_user_permissions',
            },
        ),
    ]
