# Generated by Django 4.2.7 on 2023-11-09 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '需求订单', 'verbose_name_plural': '需求订单'},
        ),
    ]
