# Generated by Django 4.2.7 on 2023-11-20 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
        ('demand', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, help_text='地址', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.address', verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='task',
            field=models.ForeignKey(blank=True, help_text='任务', null=True, on_delete=django.db.models.deletion.SET_NULL, to='demand.task', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
