# Generated by Django 3.2.23 on 2023-11-23 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0002_alter_file_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(help_text='分类名称', max_length=20, verbose_name='分类名称')),
                ('image', models.ImageField(blank=True, help_text='分类图片', null=True, upload_to='good/group', verbose_name='分类图片')),
                ('status', models.BooleanField(default=True, help_text='是否显示', verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'ta_goods_group',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(help_text='商品标题', max_length=20, verbose_name='商品标题')),
                ('desc', models.CharField(help_text='商品描述', max_length=50, verbose_name='商品描述')),
                ('price', models.DecimalField(decimal_places=2, help_text='商品价格', max_digits=10, verbose_name='商品价格')),
                ('cover', models.ImageField(blank=True, help_text='商品封面', null=True, upload_to='good', verbose_name='商品封面')),
                ('stock', models.IntegerField(default=0, help_text='商品库存', verbose_name='商品库存')),
                ('status', models.BooleanField(default=True, help_text='审核状态', verbose_name='审核状态')),
                ('is_on_sale', models.BooleanField(default=True, help_text='是否上架', verbose_name='是否上架')),
                ('recommend', models.BooleanField(default=False, help_text='是否推荐', verbose_name='是否推荐')),
                ('group', models.ForeignKey(help_text='商品分类', on_delete=django.db.models.deletion.CASCADE, to='good.goodsgroup', verbose_name='商品分类')),
                ('images', models.ManyToManyField(blank=True, help_text='商品图片', to='file.File', verbose_name='商品图片')),
                ('school', models.ForeignKey(help_text='学校', on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='学校')),
                ('user', models.ForeignKey(help_text='上传用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'ta_goods',
            },
        ),
    ]
