# Generated by Django 4.2.7 on 2023-11-08 09:07

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(help_text='商品标题', max_length=20, verbose_name='商品标题')),
                ('desc', models.CharField(help_text='商品描述', max_length=50, verbose_name='商品描述')),
                ('price', models.DecimalField(decimal_places=2, help_text='商品价格', max_digits=10, verbose_name='商品价格')),
                ('cover', models.ImageField(blank=True, help_text='商品封面', null=True, upload_to='good', verbose_name='商品封面')),
                ('stock', models.IntegerField(default=0, help_text='商品库存', verbose_name='商品库存')),
                ('is_on_sale', models.BooleanField(default=True, help_text='是否上架', verbose_name='是否上架')),
                ('recommend', models.BooleanField(default=False, help_text='是否推荐', verbose_name='是否推荐')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'ta_goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(help_text='轮播标题', max_length=20, verbose_name='轮播标题')),
                ('image', models.ImageField(blank=True, help_text='商品轮播图', null=True, upload_to='good/banner', verbose_name='商品轮播图')),
                ('seq', models.IntegerField(default=0, help_text='轮播顺序', verbose_name='轮播顺序')),
                ('status', models.BooleanField(default=True, help_text='是否显示', verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '商品轮播图',
                'verbose_name_plural': '商品轮播图',
                'db_table': 'ta_goods_banner',
            },
        ),
        migrations.CreateModel(
            name='GoodsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(help_text='分类名称', max_length=20, verbose_name='分类名称')),
                ('image', models.ImageField(blank=True, help_text='分类图片', null=True, upload_to='good/group', verbose_name='分类图片')),
                ('status', models.BooleanField(default=True, help_text='是否显示', verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'ta_goods_group',
            },
        ),
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('producer', models.CharField(help_text='生产厂家', max_length=20, verbose_name='生产厂家')),
                ('norms', models.CharField(help_text='商品规格', max_length=20, verbose_name='商品规格')),
                ('detail', ckeditor.fields.RichTextField(blank=True, help_text='商品详情', null=True, verbose_name='商品详情')),
                ('goods', models.OneToOneField(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='good.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品详情',
                'verbose_name_plural': '商品详情',
                'db_table': 'ta_goods_detail',
            },
        ),
        migrations.CreateModel(
            name='GoodsCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('goods', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='good.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品收藏',
                'verbose_name_plural': '商品收藏',
                'db_table': 'ta_goods_collection',
            },
        ),
    ]
