# Generated by Django 4.2.7 on 2023-11-20 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('good', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='school',
            field=models.ForeignKey(help_text='学校', on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='学校'),
        ),
    ]
