# Generated by Django 4.2.7 on 2023-11-08 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscollection',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='goods',
            name='group',
            field=models.ForeignKey(help_text='商品分类', on_delete=django.db.models.deletion.CASCADE, to='good.goodsgroup', verbose_name='商品分类'),
        ),
        migrations.AddField(
            model_name='goods',
            name='school',
            field=models.ForeignKey(help_text='学校', on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='学校'),
        ),
    ]
