# Generated by Django 4.2.7 on 2023-11-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsdetail',
            name='goods',
        ),
        migrations.DeleteModel(
            name='GoodsCollection',
        ),
        migrations.DeleteModel(
            name='GoodsDetail',
        ),
    ]
