# Generated by Django 4.2.7 on 2023-11-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoodsBanner',
        ),
    ]
