# Generated by Django 3.2.23 on 2023-11-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0003_auto_20231123_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='cover',
        ),
    ]
