# Generated by Django 4.2.7 on 2023-11-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_alter_file_file'),
        ('good', '0003_delete_goodsbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='商品图片', to='file.file', verbose_name='商品图片'),
        ),
    ]
