# Generated by Django 3.2.23 on 2023-11-23 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_initial'),
        ('good', '0004_remove_goods_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsgroup',
            name='school',
            field=models.ForeignKey(default=1, help_text='学校', on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='学校'),
            preserve_default=False,
        ),
    ]
