# Generated by Django 3.2.23 on 2023-11-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0005_goodsgroup_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='contact',
            field=models.CharField(default='', help_text='联系方式', max_length=20, verbose_name='联系方式'),
        ),
    ]
