# Generated by Django 4.2.7 on 2023-11-09 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('subject', models.CharField(max_length=200, verbose_name='主题')),
                ('content', models.TextField(verbose_name='内容')),
                ('message_type', models.CharField(choices=[('like', '点赞'), ('comment', '评论')], max_length=10, verbose_name='消息类型')),
                ('related_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('recipients', models.ManyToManyField(blank=True, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '站内信',
                'verbose_name_plural': '站内信',
            },
        ),
    ]
