# Generated by Django 4.2.7 on 2023-11-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0003_announcement_notice_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='系统名称')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/%Y/%m/%d/', verbose_name='系统LOGO')),
                ('site_description', models.TextField(blank=True, null=True, verbose_name='系统描述')),
                ('site_keywords', models.TextField(blank=True, null=True, verbose_name='系统关键词')),
                ('site_icp', models.CharField(blank=True, max_length=200, null=True, verbose_name='系统备案号')),
                ('site_copy', models.CharField(blank=True, max_length=200, null=True, verbose_name='系统版权')),
                ('site_status', models.BooleanField(default=True, verbose_name='系统状态')),
                ('site_close_reason', models.TextField(blank=True, null=True, verbose_name='系统关闭原因')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
    ]
