# Generated by Django 4.2.7 on 2023-11-10 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0004_siteconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_pay_mch_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='微信支付商户号')),
                ('wechat_pay_api_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='微信支付API密钥')),
                ('wechat_name', models.CharField(max_length=200, verbose_name='微信公众号名称')),
                ('wechat_qrcode', models.ImageField(blank=True, null=True, upload_to='wechat/%Y/%m/%d/', verbose_name='微信公众号二维码')),
                ('wechat_appid', models.CharField(blank=True, max_length=200, null=True, verbose_name='微信公众号AppID')),
                ('wechat_appsecret', models.CharField(blank=True, max_length=200, null=True, verbose_name='微信公众号AppSecret')),
                ('wechat_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='微信公众号Token')),
                ('wechat_app_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='小程序名字')),
                ('wechat_app_appid', models.CharField(blank=True, max_length=200, null=True, verbose_name='小程序AppID')),
                ('wechat_app_appsecret', models.CharField(blank=True, max_length=200, null=True, verbose_name='小程序AppSecret')),
                ('site_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wechat_configuration', to='global.siteconfiguration', verbose_name='关联的系统配置')),
            ],
            options={
                'verbose_name': '微信配置',
                'verbose_name_plural': '微信配置',
            },
        ),
    ]
