# Generated by Django 4.2.7 on 2023-11-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0006_remove_siteconfiguration_site_close_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qiniuconfiguration',
            name='qiniu_enable',
            field=models.BooleanField(default=False, verbose_name='是否使用七牛云存储'),
        ),
    ]
