# Generated by Django 4.2.7 on 2023-11-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0008_appconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('carousel_name', models.CharField(max_length=200, verbose_name='轮播图名称')),
                ('carousel_image', models.ImageField(blank=True, null=True, upload_to='carousel/%Y/%m/%d/', verbose_name='轮播图图片')),
                ('carousel_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='轮播图链接')),
                ('carousel_status', models.BooleanField(default=True, verbose_name='轮播图状态')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='UserCenterConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_center_vip', models.BooleanField(default=True, verbose_name='个人vip标签是否显示')),
                ('user_center_wallet', models.BooleanField(default=True, verbose_name='个人钱包是否显示')),
                ('app_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_center_configuration', to='global.appconfiguration', verbose_name='关联的app配置')),
            ],
            options={
                'verbose_name': '个人中心配置',
                'verbose_name_plural': '个人中心配置',
            },
        ),
        migrations.CreateModel(
            name='IndexConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='首页title')),
                ('index_description', models.TextField(blank=True, null=True, verbose_name='首页description')),
                ('index_activity_bg', models.ImageField(blank=True, null=True, upload_to='index/%Y/%m/%d/', verbose_name='首页活动背景图')),
                ('index_idle_bg', models.ImageField(blank=True, null=True, upload_to='index/%Y/%m/%d/', verbose_name='首页闲置背景图')),
                ('index_demand_bg', models.ImageField(blank=True, null=True, upload_to='index/%Y/%m/%d/', verbose_name='首页需求背景图')),
                ('index_demand_publish_bg', models.ImageField(blank=True, null=True, upload_to='index/%Y/%m/%d/', verbose_name='首页需求发布背景图')),
                ('index_ai_bg', models.ImageField(blank=True, null=True, upload_to='index/%Y/%m/%d/', verbose_name='首页ai背景图')),
                ('app_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='index_configuration', to='global.appconfiguration', verbose_name='关联的app配置')),
                ('index_carousel', models.ManyToManyField(blank=True, related_name='index_carousel', to='global.carousel', verbose_name='首页轮播图')),
            ],
            options={
                'verbose_name': '首页配置',
                'verbose_name_plural': '首页配置',
            },
        ),
    ]
