# Generated by Django 4.2.7 on 2023-11-20 05:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('detail', ckeditor.fields.RichTextField(blank=True, help_text='公告详情', null=True, verbose_name='公告详情')),
                ('notice_time', models.DateTimeField(blank=True, null=True, verbose_name='通知时间')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
            },
        ),
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200, verbose_name='app名称')),
                ('app_description', models.TextField(blank=True, null=True, verbose_name='app描述')),
                ('app_status', models.BooleanField(default=True, verbose_name='app状态')),
                ('app_logo', models.ImageField(blank=True, null=True, upload_to='app/%Y/%m/%d/', verbose_name='applogo')),
                ('app_bind_phone', models.BooleanField(default=True, verbose_name='手机号是否必绑定')),
                ('app_bind_email', models.BooleanField(default=True, verbose_name='邮箱是否必绑定')),
                ('app_post_audit', models.BooleanField(default=True, verbose_name='帖子是否需要审核')),
                ('app_activity_audit', models.BooleanField(default=True, verbose_name='活动是否需要审核')),
                ('app_idle_audit', models.BooleanField(default=True, verbose_name='闲置是否需要审核')),
                ('app_demand_audit', models.BooleanField(default=True, verbose_name='需求是否需要审核')),
                ('app_comment_audit', models.BooleanField(default=True, verbose_name='评论是否需要审核')),
                ('app_post_anonymous', models.BooleanField(default=True, verbose_name='帖子匿名是否开启')),
                ('app_comment_anonymous', models.BooleanField(default=True, verbose_name='评论匿名是否开启')),
            ],
            options={
                'verbose_name': 'app配置',
                'verbose_name_plural': 'app配置',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('carousel_name', models.CharField(max_length=200, verbose_name='轮播图名称')),
                ('carousel_image', models.ImageField(blank=True, null=True, upload_to='carousel/%Y/%m/%d/', verbose_name='轮播图图片')),
                ('carousel_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='轮播图链接')),
                ('carousel_status', models.BooleanField(default=True, verbose_name='轮播图状态')),
                ('carousel_order', models.IntegerField(default=0, verbose_name='轮播图排序')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(blank=True, max_length=200, null=True, verbose_name='邮箱服务器')),
                ('email_port', models.CharField(blank=True, max_length=200, null=True, verbose_name='邮箱端口')),
                ('email_host_user', models.CharField(blank=True, max_length=200, null=True, verbose_name='发送邮件的邮箱')),
                ('email_host_password', models.CharField(blank=True, max_length=200, null=True, verbose_name='在邮箱中设置的客户端授权密码')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='是否使用了SSL或者TLS')),
            ],
            options={
                'verbose_name': '邮箱配置',
                'verbose_name_plural': '邮箱配置',
            },
        ),
        migrations.CreateModel(
            name='IndexConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='首页title')),
                ('index_description', models.TextField(blank=True, null=True, verbose_name='首页description')),
                ('index_activity_bg', models.ImageField(blank=True, null=True, upload_to='index/%Y/%m/%d/', verbose_name='首页活动背景图')),
                ('index_idle_bg', models.ImageField(blank=True, null=True, upload_to='index/%Y/%m/%d/', verbose_name='首页闲置背景图')),
                ('index_demand_bg', models.ImageField(blank=True, null=True, upload_to='index/%Y/%m/%d/', verbose_name='首页需求背景图')),
                ('index_demand_publish_bg', models.ImageField(blank=True, null=True, upload_to='index/%Y/%m/%d/', verbose_name='首页需求发布背景图')),
                ('index_ai_bg', models.ImageField(blank=True, null=True, upload_to='index/%Y/%m/%d/', verbose_name='首页ai背景图')),
            ],
            options={
                'verbose_name': '首页配置',
                'verbose_name_plural': '首页配置',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('subject', models.CharField(max_length=200, verbose_name='主题')),
                ('content', models.TextField(verbose_name='内容')),
                ('message_type', models.CharField(choices=[('like', '点赞'), ('comment', '评论')], max_length=10, verbose_name='消息类型')),
                ('related_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
            ],
            options={
                'verbose_name': '站内信',
                'verbose_name_plural': '站内信',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='系统名称')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/%Y/%m/%d/', verbose_name='系统LOGO')),
                ('site_description', models.TextField(blank=True, null=True, verbose_name='系统描述')),
                ('site_icp', models.CharField(blank=True, max_length=200, null=True, verbose_name='系统备案号')),
                ('site_status', models.BooleanField(default=True, verbose_name='系统状态')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
        migrations.CreateModel(
            name='WeChatConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_pay_mch_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='微信支付商户号')),
                ('wechat_pay_api_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='微信支付API密钥')),
                ('wechat_name', models.CharField(max_length=200, verbose_name='微信公众号名称')),
                ('wechat_qrcode', models.ImageField(blank=True, null=True, upload_to='wechat/%Y/%m/%d/', verbose_name='微信公众号二维码')),
                ('wechat_appid', models.CharField(blank=True, max_length=200, null=True, verbose_name='微信公众号AppID')),
                ('wechat_appsecret', models.CharField(blank=True, max_length=200, null=True, verbose_name='微信公众号AppSecret')),
                ('wechat_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='微信公众号Token')),
                ('wechat_app_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='小程序名字')),
                ('wechat_app_appid', models.CharField(blank=True, max_length=200, null=True, verbose_name='小程序AppID')),
                ('wechat_app_appsecret', models.CharField(blank=True, max_length=200, null=True, verbose_name='小程序AppSecret')),
                ('site_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wechat_configuration', to='global_system.siteconfiguration', verbose_name='关联的系统配置')),
            ],
            options={
                'verbose_name': '微信配置',
                'verbose_name_plural': '微信配置',
            },
        ),
        migrations.CreateModel(
            name='UserCenterConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_center_vip', models.BooleanField(default=False, verbose_name='个人vip标签是否显示')),
                ('user_center_wallet', models.BooleanField(default=False, verbose_name='个人钱包是否显示')),
                ('app_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_center_configuration', to='global_system.appconfiguration', verbose_name='关联的app配置')),
            ],
            options={
                'verbose_name': '个人中心配置',
                'verbose_name_plural': '个人中心配置',
            },
        ),
        migrations.CreateModel(
            name='SMSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tencent_sms_app_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='短信应用SDK AppID')),
                ('tencent_sms_app_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='短信应用SDK AppKey')),
                ('tencent_sms_sign', models.CharField(blank=True, max_length=200, null=True, verbose_name='短信签名内容')),
                ('tencent_sms_template_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='短信模板ID')),
                ('tencent_sms_secretid', models.CharField(blank=True, max_length=200, null=True, verbose_name='短信应用secretid')),
                ('tencent_sms_secretkey', models.CharField(blank=True, max_length=200, null=True, verbose_name='短信应用secretkey')),
                ('site_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_configuration', to='global_system.siteconfiguration', verbose_name='关联的系统配置')),
            ],
            options={
                'verbose_name': '短信配置',
                'verbose_name_plural': '短信配置',
            },
        ),
        migrations.CreateModel(
            name='QQConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq_appid', models.CharField(blank=True, max_length=200, null=True, verbose_name='QQ登录APPID')),
                ('qq_appkey', models.CharField(blank=True, max_length=200, null=True, verbose_name='QQ登录APPKEY')),
                ('site_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qq_configuration', to='global_system.siteconfiguration', verbose_name='关联的系统配置')),
            ],
            options={
                'verbose_name': 'QQ配置',
                'verbose_name_plural': 'QQ配置',
            },
        ),
        migrations.CreateModel(
            name='QiniuConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiniu_access_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='七牛云AccessKey')),
                ('qiniu_secret_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='七牛云SecretKey')),
                ('qiniu_bucket_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='七牛云存储空间名称')),
                ('qiniu_bucket_domain', models.CharField(blank=True, max_length=200, null=True, verbose_name='七牛云存储空间域名')),
                ('qiniu_enable', models.BooleanField(default=False, verbose_name='是否使用七牛云存储')),
                ('site_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qiniu_configuration', to='global_system.siteconfiguration', verbose_name='关联的系统配置')),
            ],
            options={
                'verbose_name': '七牛云配置',
                'verbose_name_plural': '七牛云配置',
            },
        ),
    ]
