# Generated by Django 4.2.7 on 2023-11-20 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('global_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='接收人'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送者'),
        ),
        migrations.AddField(
            model_name='indexconfiguration',
            name='app_configuration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='index_configuration', to='global_system.appconfiguration', verbose_name='关联的app配置'),
        ),
        migrations.AddField(
            model_name='indexconfiguration',
            name='index_carousel',
            field=models.ManyToManyField(blank=True, related_name='index_carousel', to='global_system.carousel', verbose_name='首页轮播图'),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='site_configuration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_configuration', to='global_system.siteconfiguration', verbose_name='关联的系统配置'),
        ),
    ]
