# Generated by Django 4.2.7 on 2023-11-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_system', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='notice_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='通知时间'),
        ),
    ]
