# Generated by Django 4.2.7 on 2023-11-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_system', '0007_qiniuconfiguration_qiniu_enable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200, verbose_name='app名称')),
                ('app_description', models.TextField(blank=True, null=True, verbose_name='app描述')),
                ('app_status', models.BooleanField(default=True, verbose_name='app状态')),
                ('app_logo', models.ImageField(blank=True, null=True, upload_to='app/%Y/%m/%d/', verbose_name='applogo')),
                ('app_bind_phone', models.BooleanField(default=True, verbose_name='手机号是否必绑定')),
                ('app_bind_email', models.BooleanField(default=True, verbose_name='邮箱是否必绑定')),
                ('app_post_audit', models.BooleanField(default=True, verbose_name='帖子是否需要审核')),
                ('app_activity_audit', models.BooleanField(default=True, verbose_name='活动是否需要审核')),
                ('app_idle_audit', models.BooleanField(default=True, verbose_name='闲置是否需要审核')),
            ],
            options={
                'verbose_name': 'app配置',
                'verbose_name_plural': 'app配置',
            },
        ),
    ]
