# Generated by Django 4.2.7 on 2023-11-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_system', '0009_carousel_usercenterconfiguration_indexconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercenterconfiguration',
            name='user_center_vip',
            field=models.BooleanField(default=False, verbose_name='个人vip标签是否显示'),
        ),
        migrations.AlterField(
            model_name='usercenterconfiguration',
            name='user_center_wallet',
            field=models.BooleanField(default=False, verbose_name='个人钱包是否显示'),
        ),
    ]
