# Generated by Django 4.2.7 on 2023-11-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_system', '0010_alter_usercenterconfiguration_user_center_vip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='carousel_order',
            field=models.IntegerField(default=0, verbose_name='轮播图排序'),
        ),
    ]
