# Generated by Django 4.2.7 on 2023-11-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_system', '0011_carousel_carousel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='app_comment_anonymous',
            field=models.BooleanField(default=True, verbose_name='评论匿名是否开启'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='app_comment_audit',
            field=models.BooleanField(default=True, verbose_name='评论是否需要审核'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='app_demand_audit',
            field=models.BooleanField(default=True, verbose_name='需求是否需要审核'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='app_post_anonymous',
            field=models.BooleanField(default=True, verbose_name='帖子匿名是否开启'),
        ),
    ]
