# Generated by Django 4.2.7 on 2023-11-13 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(help_text='文章标题', max_length=50, verbose_name='文章标题')),
                ('content', models.TextField(help_text='文章内容', verbose_name='文章内容')),
                ('status', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('is_top', models.BooleanField(default=False, help_text='是否置顶', verbose_name='是否置顶')),
                ('is_hot', models.BooleanField(default=False, help_text='是否热门', verbose_name='是否热门')),
                ('is_anonymous', models.BooleanField(default=False, help_text='是否匿名', verbose_name='是否匿名')),
                ('is_audit', models.IntegerField(choices=[(0, '未审核'), (1, '审核通过'), (2, '审核未通过')], default=1, help_text='审核状态', verbose_name='审核状态')),
                ('audit_user', models.ForeignKey(help_text='审核人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_articles', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '文章帖子',
                'verbose_name_plural': '文章帖子',
                'db_table': 'ta_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('article', models.ForeignKey(help_text='文章', on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='文章')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '浏览',
                'verbose_name_plural': '浏览',
                'db_table': 'ta_article_view',
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('article', models.ForeignKey(help_text='文章', on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='文章')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'db_table': 'ta_article_like',
            },
        ),
        migrations.CreateModel(
            name='ArticleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('file', models.FileField(help_text='文件', upload_to='article_files/', verbose_name='文件')),
                ('article', models.ForeignKey(help_text='帖子', on_delete=django.db.models.deletion.CASCADE, related_name='article_files', to='article.article', verbose_name='帖子')),
            ],
            options={
                'verbose_name': '帖子文件',
                'verbose_name_plural': '帖子文件',
                'db_table': 'ta_article_file',
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(help_text='评论内容', verbose_name='评论内容')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('article', models.ForeignKey(help_text='文章', on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='文章')),
                ('parent', models.ForeignKey(blank=True, help_text='父级评论', null=True, on_delete=django.db.models.deletion.CASCADE, to='article.articlecomment', verbose_name='父级评论')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'ta_article_comment',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='files',
            field=models.ManyToManyField(help_text='文件', related_name='article_files', to='article.articlefile', verbose_name='文件'),
        ),
        migrations.AddField(
            model_name='article',
            name='school',
            field=models.ForeignKey(help_text='学校', on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='学校'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, related_name='user_articles', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
