# Generated by Django 4.2.7 on 2023-11-20 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(help_text='文章内容', verbose_name='文章内容')),
                ('status', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('is_top', models.BooleanField(default=False, help_text='是否置顶', verbose_name='是否置顶')),
                ('is_hot', models.BooleanField(default=False, help_text='是否热门', verbose_name='是否热门')),
                ('is_anonymous', models.BooleanField(default=False, help_text='是否匿名', verbose_name='是否匿名')),
                ('is_audit', models.IntegerField(choices=[(0, '未审核'), (1, '审核通过'), (2, '审核未通过')], default=1, help_text='审核状态', verbose_name='审核状态')),
            ],
            options={
                'verbose_name': '文章帖子',
                'verbose_name_plural': '文章帖子',
                'db_table': 'ta_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(help_text='评论内容', verbose_name='评论内容')),
                ('is_anonymous', models.BooleanField(default=False, help_text='是否匿名', verbose_name='是否匿名')),
                ('is_audit', models.IntegerField(choices=[(0, '未审核'), (1, '审核通过'), (2, '审核未通过')], default=1, help_text='审核状态', verbose_name='审核状态')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'ta_article_comment',
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'db_table': 'ta_article_like',
            },
        ),
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('article', models.ForeignKey(help_text='文章', on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='文章')),
            ],
            options={
                'verbose_name': '浏览',
                'verbose_name_plural': '浏览',
                'db_table': 'ta_article_view',
            },
        ),
    ]
