# Generated by Django 4.2.7 on 2023-11-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlefile',
            name='article',
        ),
        migrations.AlterField(
            model_name='article',
            name='files',
            field=models.ManyToManyField(help_text='文件', related_name='articles', to='article.articlefile', verbose_name='文件'),
        ),
    ]
