# Generated by Django 4.2.7 on 2023-11-15 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='files',
            field=models.ForeignKey(blank=True, help_text='文件', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='article.articlefile', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='articlefile',
            name='article',
            field=models.ManyToManyField(help_text='文章', related_name='filesArticle', to='article.article', verbose_name='文章'),
        ),
    ]
