# Generated by Django 4.2.7 on 2023-11-20 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
        ('school', '0001_initial'),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleview',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='articlelike',
            name='article',
            field=models.ForeignKey(help_text='文章', on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='articlelike',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='article',
            field=models.ForeignKey(help_text='文章', on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='父级评论', null=True, on_delete=django.db.models.deletion.CASCADE, to='article.articlecomment', verbose_name='父级评论'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='article',
            name='audit_user',
            field=models.ForeignKey(help_text='审核人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_articles', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='article',
            name='files',
            field=models.ManyToManyField(blank=True, help_text='文件', related_name='files', to='file.file', verbose_name='文件'),
        ),
        migrations.AddField(
            model_name='article',
            name='school',
            field=models.ForeignKey(help_text='学校', on_delete=django.db.models.deletion.CASCADE, related_name='school_articles', to='school.school', verbose_name='学校'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, related_name='user_articles', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
