# Generated by Django 4.2.7 on 2023-11-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_files_alter_articlefile_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlefile',
            name='article',
        ),
        migrations.RemoveField(
            model_name='article',
            name='files',
        ),
        migrations.AddField(
            model_name='article',
            name='files',
            field=models.ManyToManyField(blank=True, help_text='文件', null=True, related_name='files', to='article.articlefile', verbose_name='文件'),
        ),
    ]
