# Generated by Django 4.2.7 on 2023-11-13 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_initial'),
        ('article', '0002_remove_articlefile_article_alter_article_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='files',
            field=models.ManyToManyField(blank=True, help_text='文件', related_name='articles', to='article.articlefile', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='article',
            name='school',
            field=models.ForeignKey(help_text='学校', on_delete=django.db.models.deletion.CASCADE, related_name='school_articles', to='school.school', verbose_name='学校'),
        ),
    ]
