# Generated by Django 4.2.7 on 2023-11-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_filetest_posttest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttest',
            name='files',
        ),
        migrations.DeleteModel(
            name='FileTest',
        ),
        migrations.DeleteModel(
            name='PostTest',
        ),
    ]
