# Generated by Django 4.2.7 on 2023-11-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_files_alter_article_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='is_audit',
            field=models.IntegerField(choices=[(0, '未审核'), (1, '审核通过'), (2, '审核未通过')], default=1, help_text='审核状态', verbose_name='审核状态'),
        ),
    ]
