# Generated by Django 4.2.7 on 2023-11-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_articlefile_article_remove_article_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
    ]
