# Generated by Django 4.2.7 on 2023-11-08 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(help_text='任务标题', max_length=100, verbose_name='任务标题')),
                ('description', models.TextField(help_text='任务描述', verbose_name='任务描述')),
                ('type', models.CharField(choices=[('delivery', '代取快递'), ('errand', '跑腿')], help_text='任务类型', max_length=50, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('open', '开放'), ('closed', '关闭')], default='open', help_text='状态', max_length=50, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('creator', models.ForeignKey(help_text='创建者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
        migrations.CreateModel(
            name='TaskUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, help_text='接受时间', verbose_name='接受时间')),
                ('task', models.ForeignKey(help_text='任务', on_delete=django.db.models.deletion.CASCADE, to='demand.task', verbose_name='任务')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '任务接受者',
                'verbose_name_plural': '任务接受者',
            },
        ),
        migrations.CreateModel(
            name='ErrandTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('start_location', models.CharField(help_text='开始地点', max_length=200, verbose_name='开始地点')),
                ('end_location', models.CharField(help_text='结束地点', max_length=200, verbose_name='结束地点')),
                ('task', models.OneToOneField(help_text='任务', on_delete=django.db.models.deletion.CASCADE, to='demand.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '跑腿任务',
                'verbose_name_plural': '跑腿任务',
            },
        ),
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('package_size', models.CharField(help_text='包裹大小', max_length=50, verbose_name='包裹大小')),
                ('package_weight', models.CharField(help_text='包裹重量', max_length=50, verbose_name='包裹重量')),
                ('pickup_location', models.CharField(help_text='取件地点', max_length=200, verbose_name='取件地点')),
                ('task', models.OneToOneField(help_text='任务', on_delete=django.db.models.deletion.CASCADE, to='demand.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '代取快递任务',
                'verbose_name_plural': '代取快递任务',
            },
        ),
    ]
