# Generated by Django 4.2.7 on 2023-11-20 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('package_size', models.CharField(choices=[('small', '小件'), ('medium', '中件'), ('large', '大件')], help_text='包裹大小', max_length=50, verbose_name='包裹大小')),
                ('package_image', models.ImageField(blank=True, help_text='取件信息图片', null=True, upload_to='delivery', verbose_name='取件信息图片')),
                ('package_info', models.CharField(blank=True, help_text='取件信息', max_length=200, null=True, verbose_name='取件信息')),
                ('pickup_location', models.CharField(blank=True, help_text='取件地点', max_length=200, null=True, verbose_name='取件地点')),
                ('expected_time', models.CharField(choices=[('unlimited', '不限制'), ('asap', '尽快送达'), ('today_12', '今天中午12点前'), ('today_18', '今天下午6点前'), ('today_22', '今天晚上10点前'), ('other', '其他时间请备注')], default='unlimited', help_text='期望送达时间', max_length=50, verbose_name='期望送达时间')),
                ('gender', models.CharField(choices=[('unlimited', '不限制'), ('man', '男'), ('girl', '女')], default='unlimited', help_text='性别要求', max_length=50, verbose_name='性别要求')),
            ],
            options={
                'verbose_name': '代取快递任务',
                'verbose_name_plural': '代取快递任务',
            },
        ),
        migrations.CreateModel(
            name='ErrandTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('start_location', models.CharField(help_text='开始地点', max_length=200, verbose_name='开始地点')),
                ('end_location', models.CharField(help_text='结束地点', max_length=200, verbose_name='结束地点')),
            ],
            options={
                'verbose_name': '跑腿任务',
                'verbose_name_plural': '跑腿任务',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(help_text='任务标题', max_length=100, verbose_name='任务标题')),
                ('description', models.TextField(help_text='任务描述', verbose_name='任务描述')),
                ('type', models.CharField(choices=[('delivery', '代取快递'), ('errand', '跑腿')], help_text='任务类型', max_length=50, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('open', '正常'), ('closed', '关闭'), ('expired', '过期')], default='open', help_text='状态', max_length=50, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, help_text='佣金', max_digits=10, verbose_name='佣金')),
                ('remark', models.TextField(blank=True, help_text='备注', null=True, verbose_name='备注')),
                ('deadline', models.DateTimeField(blank=True, help_text='截至时间', null=True, verbose_name='截至时间')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
        migrations.CreateModel(
            name='TaskUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, help_text='接受时间', verbose_name='接受时间')),
                ('task', models.ForeignKey(help_text='任务', on_delete=django.db.models.deletion.CASCADE, to='demand.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务接受者',
                'verbose_name_plural': '任务接受者',
            },
        ),
    ]
