# Generated by Django 4.2.7 on 2023-11-20 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskuser',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(help_text='创建者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='errandtask',
            name='task',
            field=models.OneToOneField(help_text='任务', on_delete=django.db.models.deletion.CASCADE, to='demand.task', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='task',
            field=models.OneToOneField(help_text='任务', on_delete=django.db.models.deletion.CASCADE, to='demand.task', verbose_name='任务'),
        ),
    ]
