# Generated by Django 4.2.7 on 2023-11-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverytask',
            name='package_weight',
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='additional_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='追加佣金', max_digits=10, verbose_name='追加佣金'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='佣金', max_digits=10, verbose_name='佣金'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='expected_time',
            field=models.CharField(choices=[('unlimited', '不限制'), ('asap', '尽快送达'), ('today_12', '今天中午12点前'), ('today_18', '今天下午6点前'), ('today_22', '今天晚上10点前'), ('other', '其他时间请备注')], default='unlimited', help_text='期望送达时间', max_length=50, verbose_name='期望送达时间'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='gender',
            field=models.CharField(choices=[('unlimited', '不限制'), ('man', '男'), ('girl', '女')], default='unlimited', help_text='性别要求', max_length=50, verbose_name='性别要求'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='package_image',
            field=models.ImageField(blank=True, help_text='取件信息图片', null=True, upload_to='delivery', verbose_name='取件信息图片'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='package_info',
            field=models.CharField(blank=True, help_text='取件信息', max_length=200, null=True, verbose_name='取件信息'),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='package_size',
            field=models.CharField(choices=[('small', '小件'), ('medium', '中件'), ('large', '大件')], help_text='包裹大小', max_length=50, verbose_name='包裹大小'),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='pickup_location',
            field=models.CharField(blank=True, help_text='取件地点', max_length=200, null=True, verbose_name='取件地点'),
        ),
    ]
