# Generated by Django 4.2.7 on 2023-11-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_remove_deliverytask_package_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverytask',
            name='additional_commission',
        ),
        migrations.RemoveField(
            model_name='deliverytask',
            name='commission',
        ),
        migrations.AddField(
            model_name='task',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='佣金', max_digits=10, verbose_name='佣金'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='截至时间', null=True, verbose_name='截至时间'),
        ),
        migrations.AddField(
            model_name='task',
            name='remark',
            field=models.TextField(blank=True, help_text='备注', null=True, verbose_name='备注'),
        ),
    ]
