# Generated by Django 4.2.7 on 2023-11-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0003_remove_deliverytask_additional_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', '正常'), ('closed', '关闭'), ('expired', '过期')], default='open', help_text='状态', max_length=50, verbose_name='状态'),
        ),
    ]
